### ISSUE TITLE
Add example flow for amqp-out node

### ISSUE THREAD

**Issue by UNOPARATOR** [MeowWolf/node-red-contrib-amqp#14] opened 2020-06-19 21:39 UTC
Can you please provide a working example for *amqp-out* node when you have the time?
_(Just like you did with the *amqp-in-manual-ack* node)_

**Comment by amodelbello** [comment] 2020-07-06 19:37
Hi @UNOPARATOR, sorry for the late response. I'm not sure adding an example for the amqp-out node would be much value. There's really nothing to it as long as it's configured correctly. It would just be an amqp node connected to a debug node. Unless I'm misunderstanding?

**Comment by UNOPARATOR** [comment] 2020-07-06 22:49
Well, I've been using the amqp-in & amqp-in-manuel-ack nodes for awhile now without any problems.
But I cannot make the amqp-put node work at all, even though it says connected.
It is using the same amqp-config node.
I don't know if the payload must be in a specific model or not which is the only thing that I could think of for a probable cause.
Hence the reason that I'm asking for a working sample in order to see what I'm missing. ;)

P.S: There is no output from the amqp-out node, so I don't know how I would be able to connect it to a debug node.

**Comment by amodelbello** [comment] 2020-07-06 23:03
oh sorry. I meant an inject node not a debug node. Would you mind sharing a screenshot of your amqp-out node config and your broker config?

**Comment by UNOPARATOR** [comment] 2020-07-07 08:01
Here is the info that you asked for:
Broker config:
![image](https://user-images.githubusercontent.com/1214176/86742456-d0b23000-c040-11ea-8ba4-42f3b8f94bc4.png)
amqp-out node:
![image](https://user-images.githubusercontent.com/1214176/86742624-ecb5d180-c040-11ea-9335-a45634fc026e.png)

Even sending a basic json via inject does not do anything. What am I doing wrong? Or maybe amqp-out does not support vhost?

**Comment by amodelbello** [comment] 2020-07-07 17:12
hmm. That looks like it should work. One thing that stands out is your use of a fanout exchange. We have pretty much been exclusively using topic exchanges so direct and fanout exchanges have not seen much use and therefore have not seen much testing. There could be a bug in there.

I'm hoping within the next few weeks to get some time to dig into this again and get it to v1 status. There are a few features I'd like to add and I will make looking in to this issue a part of that as well.

**Comment by UNOPARATOR** [comment] 2020-07-07 17:22
I'll be eagerly waiting to hear from you then.

P.S: While you are at it, be sure to let the CorrelationId (header) to be set separately (if it is not possible already). ;)

**Comment by amodelbello** [comment] 2020-07-07 17:25
There's no specific field for correlation_id in the node but you should be able to send headers along in the message itself. Does that not work for you?

**Comment by UNOPARATOR** [comment] 2020-07-07 17:27
If one can send the headers by setting msg.payload then it would be covered.
Since I couldn't test sending a message in the first place, I do not know what the payload expects or covers.

**Comment by UNOPARATOR** [comment] 2020-07-07 17:41
Here is a sample queue message that we normally send to RabbitMq in dotnet core via MassTransit:
![image](https://user-images.githubusercontent.com/1214176/86820595-f0be0f80-c091-11ea-9ad6-49aee08b31b5.png)

While using your node, which part is related to msg.payload of Node-RED? The whole payload?

**Comment by amodelbello** [comment] 2020-08-05 16:49
@UNOPARATOR - I'm unable to reproduce this unfortunately. It works for me with vhost too. Maybe update to the latest version and try again? I've added the ability to specify a `properties` object in the amqp-out node config and also as an input. You'll be able to specify a correlation_id there.

In response to:
> While using your node, which part is related to msg.payload of Node-RED? The whole payload?

The msg object is basically an amqplib object. And the payload of that object becomes the node-red payload.

Sorry I couldn't be more help. Is there anything else about your config that might be out of the ordinary that we haven't already discussed?

**Comment by amodelbello** [comment] 2020-08-05 16:52
Actually now that we have more possible inputs it might make sense to add an example node for amqp-out

**Comment by amodelbello** [comment] 2020-08-05 18:21
New examples added with:
https://github.com/MeowWolf/node-red-contrib-amqp/releases/tag/v0.6.0

Going to close this for now. @UNOPARATOR please reopen if you have any additional info.

**Closed by amodelbello** 2020-08-05 18:21 UTC

**Comment by UNOPARATOR** [comment] 2020-08-06 13:59
First of all, thank you.

Secondly, Node-RED changed the auto update feature so one must "request update" in their site.
When I checked this morning the old version was still showing there, so I requested an update and check if the new version showed up every 5-10 minutes, but after 1 hour or so it started to show 404 (https://flows.nodered.org/node/@meowwolf/node-red-contrib-amqp).

Can you please add it again?

**Comment by amodelbello** [comment] 2020-08-06 22:30
That's really odd. I'm getting a 404 too. Going to follow up in the forum.
In the meantime if you're able to manually install it should work from:
https://www.npmjs.com/package/@meowwolf/node-red-contrib-amqp

**Comment by amodelbello** [comment] 2020-08-06 23:00
@UNOPARATOR - evidently it was the perfect storm of me not knowing that you need to request an update and npm being down when the update actually happened that caused the node to 404. It's up now though.
